---

- hosts: all
  
  # pre_tasks:

  #   - name: Install pip
  #     package:
  #       name: python-pip

  #   - name: Install requirements
  #     pip:
  #       name: "{{ item }}"
  #     with_items:
  #       - pretty
  #       - netaddr
  #       - python-slugify

  post_tasks:

    - include: tests/string_util_functions.yml